Add new utility functions & refactor
Helpers
-------

Add new utility functions for running commands and scripts
Move some helpers to util.py

Workflow
--------

Write '.' to debugger on start, so real log messages start on a new line
Use root logger instead of 'workflow'
Add warn_empty() method to Workflow3

Rebuild workflow and docset

diff --git a/bin/testone b/bin/testone
--- a/bin/testone
+++ b/bin/testone
@@ -11,29 +11,57 @@ Run test script(s) with coverage for one package.
 
 Usage:
     testone <package.name> <test_script.py>...
-    testone -h|--help
+    testone -h
 
 Options:
-    -h, --help  Show this message and exit.
+    -h  Show this message and exit.
 
 Example:
-    extras/testone workflow.notify tests/test_notify.py
+    testone workflow.notify tests/test_notify.py
 
 EOS
 }
 
-log() {
-    echo "$@" > /dev/stderr
+if [ -t 1 ]; then
+  red='\033[0;31m'
+  green='\033[0;32m'
+  nc='\033[0m'
+else
+  red=
+  green=
+  nc=
+fi
+
+function log() {
+    echo "$@"
+}
+
+function fail() {
+  printf "${red}$@${nc}\n"
+}
+
+function success() {
+  printf "${green}$@${nc}\n"
 }
 
 
-if [[ "$1" = "-h" ]] || [[ "$1" = "--help" ]]; then
-	usage
-  exit 0
-fi
+while getopts ":h" opt; do
+  case $opt in
+    h)
+      usage
+      exit 0
+      ;;
+    \?)
+      log "Invalid option: -$OPTARG"
+      exit 1
+      ;;
+  esac
+done
+shift $((OPTIND-1))
+
 
 if [[ "$1" = "" ]] || [[ "$2" = "" ]]; then
-  log "ERROR: Missing argument(s)."
+  fail "missing argument(s)"
   log ""
   usage
   exit 1
@@ -42,8 +70,7 @@ fi
 package="$1"
 shift
 
-# export PYTEST_ADDOPTS="--cov-report=term"
-
+# Run tests
 pytest --cov="${package}" "$@"
 # ret1=$?
 ret1=${PIPESTATUS[0]}
@@ -51,8 +78,8 @@ ret1=${PIPESTATUS[0]}
 echo
 
 case "$ret1" in
-  0) log "TESTS OK";;
-  *) log "TESTS FAILED";;
+  0) success "TESTS OK";;
+  *) fail "TESTS FAILED";;
 esac
 
 log ""
@@ -64,9 +91,11 @@ ret2=${PIPESTATUS[0]}
 echo
 
 case "$ret2" in
-    0) log "COVERAGE OK" ;;
-    *) log "COVERAGE FAILED" ;;
+    0) success "COVERAGE OK" ;;
+    *) fail "COVERAGE FAILED" ;;
 esac
+
+coverage erase
 
 if [[ "$ret1" -ne 0 ]]; then
   exit $ret1
